start: (received | received_no_date | expected) ("from" entity ("," | "."))? purpose? ("." | ",")? time_commitment? "."? dest? registration_date LATE?

%ignore " "
%import .shared.purpose
%import .shared.money
%import .shared.registration_date
%import .shared.date
%import .shared._RECEIVED
%import .shared.dest
%import .shared.received
%import .shared.expected
%import .shared.entity
%import .shared.LATE
%import .shared.received_no_date
%import .shared.time_commitment